### ISSUE TITLE
Prusa Mini + Print Shift 5.0: Why 155mm film?

### ISSUE THREAD

**Issue by dclaze** [paenian/PrintShift#6]
I noticed in the BOM for Printshift 5.0 the required film width is 155mm, does this limit the printable surface area to 155 width?

Prusa Mini has a 180x180mm print surface so just curious if this is by design or if I should buy a wider film to get the full bed surface potential.

Reference: https://github.com/paenian/PrintShift/tree/main/prusa%20mini/printshift%205.0%20ejector

**Comment by paenian** [comment]
The film is narrower than the bed, and limits the printable area that's ejectable.  The reason for that is so you can use the existing bed mounts - the belt is narrow to squeeze between them.
