### ISSUE TITLE
Unable to find the tensioner for printshift v5

### ISSUE THREAD

**Issue by Bjerg** [paenian/PrintShift#7]
i am unable to find the file for the tensioner for the belt? for the printshift v5 am i missing something?

<img width="684" alt="image" src="https://github.com/paenian/PrintShift/assets/6697860/ae37ca15-6625-4d1d-8155-3a4ba9ece236">

**Comment by paenian** [comment]
Here's the rod mount with the tensioner: https://github.com/paenian/PrintShift/blob/main/prusa%20mini/printshift%205.0%20ejector/tensioner%20rod%20mount%20right.stl

I just used 4 of them, two normal and two mirrored.  Add a 20mm M3 bolt and square M3 nut to tension the belt against the y-axis frame.
